---
deployment:
  tasks:
    - export DEPLOYPATH=/home/semedasf/public_html/semeda
    - /usr/bin/rsync -av --delete ./ $DEPLOYPATH
    - cd $DEPLOYPATH && npm install --production
    - cd $DEPLOYPATH && npm run build
    - /usr/local/bin/ea-passenger-restart-app /home/semedasf/public_html/semeda